### ISSUE TITLE
Tests fail on Mac after storm installation

### ISSUE THREAD

**Issue by oreohere** [moves-rwth/prophesy#1]
I'm trying to install prophesy on MacOS 10.15. The output for ```python setup.py develop```  is 
[setup.log](https://github.com/moves-rwth/prophesy/files/3723792/setup.log). On running ```pytest tests``` 
[test.log](https://github.com/moves-rwth/prophesy/files/3723803/test.log). I'm not sure what I'm missing. Any help would be appreciated.

**Comment by volkm** [comment]
Thanks for the report. There was an issue with a missing setting in Storm. It should be fixed with https://github.com/moves-rwth/storm/commit/3698b79130fb9b1b65ed346faba5a3c68d6d2ea0.
To get the fix, you should pull the Storm `master` branch and rebuild it. The rebuild should only affect a couple of files and not the complete source code. Afterwards the Prophesy tests should work again.

**Comment by oreohere** [comment]
Thanks for the quick reply. That did stop the tests from failing, however, a lot of them were skipped. 
<img width="1440" alt="Screen Shot 2019-10-14 at 3 47 47 PM" src="https://user-images.githubusercontent.com/14862450/66781850-00f5e500-ee9a-11e9-9acd-b0a5ff1a7ce8.png">
I hope that'll be enough for my current research

**Comment by volkm** [comment]
Some of the tests are supposed to be skipped as they test specific configurations which require additional libraries such as Gurobi or Yices. However, it seems that most of the tests in your case are skipped because stormpy could not be found. For example, both tests in `prophesy/tests/modelcheckers/test_sampling.py` are supposed to run.
Can you check the configurations files in `prophesy/dependencies.cfg` and `prophesy/dependencies.cfg` and adapt the configurations if necessary?

**Comment by oreohere** [comment]
Thanks for the heads-up. I guess the issue was in ```prophesy/dependencies.cfg``` , stormpy was set to false. On turning it to true and providing the path (not sure if this was needed), all the tests in ```tests``` ran fine, and fewer were skipped in ```scripts/tests``` this time. 
<img width="1435" alt="Screen Shot 2019-10-15 at 3 57 00 AM" src="https://user-images.githubusercontent.com/14862450/66816763-3d5c2c00-ef00-11e9-8253-56e47ec13b4c.png">

**Comment by volkm** [comment]
That looks good. The remaining skipped tests are only needed for special configurations and can be ignored in your case.
