### ISSUE TITLE
Error while sampling

### ISSUE THREAD

**Issue by oreohere** [moves-rwth/prophesy#2]
I'm trying to run prophesy using an existing model in the benchmark folder. However I run into an issue I'm sure how to solve. 
<img width="1410" alt="Screen Shot 2019-11-01 at 1 34 12 PM" src="https://user-images.githubusercontent.com/14862450/68047397-4ee95600-fcac-11e9-9152-e6d5f14f3c16.png">

**Comment by volkm** [comment]
At the moment most of the sampling needs a threshold as additional input. This threshold is used to refine the sampling and compute more samples close to the threshold value. If you provide a threshold with the additional arguments `set-threshold 0.9` the sampling should work fine.
If no threshold is provided, it should work (since b1ecbaf1a705750de84236f181f6b893a29ef83f) as well, but no refinement takes place.
