### ISSUE TITLE
Temporary Storm result file not being created 

### ISSUE THREAD

**Issue by oreohere** [moves-rwth/prophesy#3]
I'm trying to run get a solution function, however, in spite of getting the message that the model checker ran fine, the temporary file that stores the result of the model checker isn't getting created, hence the program crashes. Let me know if I am doing something wrong.
<img width="1434" alt="Screen Shot 2019-11-01 at 1 58 34 PM" src="https://user-images.githubusercontent.com/14862450/68048971-b3f27b00-fcaf-11e9-9dd1-86a6f01f8c5f.png">

This might be stupid but the file isn't actually getting created
<img width="162" alt="Screen Shot 2019-11-01 at 1 59 19 PM" src="https://user-images.githubusercontent.com/14862450/68049047-ebf9be00-fcaf-11e9-95b8-ecf7ff7a3643.png">

**Comment by volkm** [comment]
The computation of a rational function is only supported for DTMCs. For MDPs there is a different rational function for each scheduler and we cannot compute a unique rational function.
However, the output was very misleading because the model checker did not finish successfully. I added some better error output in 965a875d0c00b7facb63363beeb5cb9f3d18382d to make clear where exactly the problem is.
